# Use an official Node.js image
FROM node:18

# Set the working directory inside the container
WORKDIR /app

# Copy package.json and package-lock.json
COPY package*.json ./

# Install dependencies
RUN apt-get update && apt-get install -y libxi-dev libx11-dev libxxf86vm-dev
RUN npm install --unsafe-perm --force

# Copy the rest of the application code
COPY . .

# Expose port 3000
EXPOSE 3000

# Command to start the app
CMD ["node", "server.js"]
